language: go
os:
  - linux
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  # Coverage
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  # Local Server setup
  - sudo apt-get install openssh-server
  - ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  - cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
  - echo "RUN ls -la" > ./Efs2file
script:
  # Check format and code cleanliness
  - gofmt -l ./ | grep -v vendor | wc -l | grep -q 0
  - go vet -v
  # Run Tests
  - make tests clean
  # Install and Test
  - make build
  - make install
  - efs2 -v localhost
after_success:
  - goveralls -coverprofile=coverage/coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
