language: go
os:
  - linux
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - sudo apt-get install openssh-server
  - ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  - cp ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
  - echo "RUN CMD ls -la" > ./Efs2file
script:
  - gofmt -l ./
  - go vet -v
  - make tests clean
  - make build
  - make install
  - efs2 -v localhost
